<form method="post" action="admin/menu/atualizar">
	<input readonly="readonly" type="text" name="id_menu" value="<?=$this->getMenuClass()->idMenu;?>" />
	<label for="">Menu Superior</label>
	<select name="id_menu_superior">
		<option value="">Selecione...</option>	
		<?php while ($this->getMenuSuperior()->next()) : ?>
		<option <?=$this->getMenuClass()->idMenuSuperior==$this->getMenuSuperior()->getValue("id_menu")
			?'selected="selected"':"" ?>
			value="<?=$this->getMenuSuperior()->getValue('id_menu'); ?>"><?=$this->getMenuSuperior()->getValue("ds_menu");?>
		</option>
		<?php endwhile; ?>
	</select>
	<label for="">Descrição</label>
	<input type="text" name="ds_menu" class="required" value="<?=$this->getMenuClass()->dsMenu;?>" />
	<label for="">URL</label>
	<input type="text" name="ds_url" class="required" value="<?=$this->getMenuClass()->dsUrl;?>" />
	<label for="">Situação</label>
	<select name="ds_situacao">
		<option value="A" <?=$this->getMenuClass()->situacao=="A"?'selected="selected"':"" ?>>Ativo</option>
		<option value="I" <?=$this->getMenuClass()->situacao=="I"?'selected="selected"':"" ?>>Inativo</option>
	</select>
	<div class="divisao">
		<input type="submit" value="Gravar" class="btn color-01" />
		<input type="reset" value="Cancelar" class="btn color-02" />
	</div>
</form>