<!DOCTYPE html>
<html lang="<?= $this->getLanguage(); ?>">
<head>
    <meta charset="<?= $this->getCharset(); ?>">
    <title><?= $this->getTitle(); ?></title>
    <base href="/"/>
    <?php $this->getStyleSheet() ?>
    <?php $this->getJavaScript() ?>
    <link rel="stylesheet" href="assets/css/admin_style.css"/>
    <link rel="stylesheet" href="assets/css/sweet-alert.css"/>
    <link rel="stylesheet" href="assets/css/jquery.contextMenu.css"/>
</head>
<body>
    <div>
        <ul>
            <li>
                <a href="admin">Home</a>
                <a href="admin/menu/listar">Adicionar Menu</a>
            </li>
        </ul>
    </div>
    <?php $this->getBody(); ?>

<script type="text/javascript" src="assets/js/jquery.min.js"></script>
<script type="text/javascript" src="assets/js/jquery.form.min.js"></script>
<script type="text/javascript" src="assets/js/main.js"></script>
<script type="text/javascript" src="assets/js/sweet-alert.min.js"></script>
<script type="text/javascript" src="assets/js/jquery.contextMenu.js"></script>
</body>
</html>