<!DOCTYPE html>
<html lang="<?= $this->getLanguage(); ?>">
    <head>
        <meta charset="<?= $this->getCharset(); ?>">
        <title><?= $this->getTitle(); ?></title>
        <base href="/"/>
        <?php $this->getStyleSheet() ?>
        <?php $this->getJavaScript() ?>
        <link rel="stylesheet" href="assets/css/style.css"/>
    </head>
    <body>
        <div id="cssmenu">
            <ul>
            <?php foreach ($this->getArrayMenu() as $key => $value) : ?>                
                <?php if (!is_null($value["sub_menu"])) { ?>
                    <li class="has-sub">
                        <a href="#">
                        <?= $value["ds_menu"]; ?>
                        </a>
                        <ul>
                        <?= $this->showMenu($value["sub_menu"]); ?>
                        </ul>
                    </li>
                <?php } else { ?>
                    <li class="active">
                        <a href="#"><?=$value['ds_menu'];?></a>
                    </li>
                <?php }
                ?>                                
            <?php endforeach; ?>
            </ul>
        </div>
        <?php $this->getBody(); ?>

        <script type="text/javascript" src="assets/js/jquery.min.js"></script>
        <script type="text/javascript" src="assets/js/jquery.form.min.js"></script>
        <script type="text/javascript" src="assets/js/main.js"></script>
        <script type="text/javascript" src="assets/js/jquery-ui.js"></script>
    </body>
</html>