<textarea id="coment-textarea" name="" cols="60" rows="5"></textarea>
<input id="coment-buttom" type="button" value="Enviar Comentário"/>
<form id="formImagem" action="publicacao/postPhoto" method="post" enctype="multipart/form-data">
    <input type="file" name="imagem[]" multiple="" onchange="enviarImagemForm();" />
</form>
<div id="galery-images">

</div>
<input value="Enviar Arte" type="button" id="enviar_arte">
<hr/>
<div id="imagem-nova">
dfgregdsfgdf
</div>